version: "3"

services:
  health:
    container_name: health
    image: nick3141/health
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - LOG_DIR=./storage/logs
      - LOG_MAX_SIZE=20m
      - LOG_ROTATION_MAX_AGE=7d
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX=100
    networks:
      - nk
    volumes:
      - ./_v_logs:/usr/src/app/storage/logs

networks:
  nk:
    driver: bridge
