version: "3"

services:
  http_icons:
    container_name: http_icons
    image: nick3141/http-icons:latest
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - LOG_DIR=./storage/logs
      - LOG_MAX_SIZE=20m
      - LOG_ROTATION_MAX_AGE=7d
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX=500
      - CACHE_VIEWS=true
      - CACHE_ASSETS=true
    networks:
      - nk
    volumes:
      - ./_v_logs:/usr/src/app/storage/logs

networks:
  nk:
    driver: bridge
